const PREFIX = 'MOVIE'

export const GET_MOVIES_SHOWING_REQUEST = `${PREFIX}/GET_MOVIES_SHOWING_REQUEST`
export const GET_MOVIES_SHOWING_SUCCESS = `${PREFIX}/GET_MOVIES_SHOWING_SUCCESS`
export const GET_MOVIES_SHOWING_FAILURE = `${PREFIX}/GET_MOVIES_SHOWING_FAILURE`